blank_issues_enabled: false
contact_links:
    - name: ğŸ’¡ Feature / Task Issue
      url: https://github.com/dbwlsyyy/lofi-player/issues/new?template=feature_task.yml
      about: ìƒˆ ê¸°ëŠ¥ì´ë‚˜ ì‘ì—…ì„ ìœ„í•œ ì´ìŠˆ ìƒì„±
